config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :validations, :only => ['new', 'update', 'edit']
  post 'validations/:id' => 'validations#create', :as => 'create_validation'
  get 'catalog/stamps/:id' => 'visitors#catalog', :as => 'catalog'
  get 'catalog/modal/:stamp_id' => 'visitors#modal', :as => 'catalog_modal'
  get '/orders/update_terms' => 'orders#update_terms'
  post '/orders/create' => 'orders#create'
  post '/create' => 'orders#create'

  resources :attachments, :only => ['create', 'update', 'edit', 'destroy']

  root to: 'admin#index'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
  			get '/angular_index', to: 'users#angular_index'
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end

  scope :users do
    post '/registration', to: 'users#register', as: "register_user"
    get '/sign_up', to: 'users#sign_up', as: "sign_up_user"
  end

  resources :ods do
    collection do
      get '/angular_index', to: 'ods#angular_index'
      get ':id/clone', to: 'ods#clone', as: 'clone'
    end
  end

  resources :reorders, only: [:update, :edit, :destroy, :index, :show] do 
    collection do
      get '/angular_index', to: 'reorders#angular_index'
      post ':id/changed_status/:stat', to: 'reorders#changed_status', as: 'changed_status'
      post '/delete', to: 'reorders#delete'
    end
  end

  resources :orders, only: [:new, :create]

  scope :admin do
    resources :stamps do
      collection do
        get '/angular_index', to: 'stamps#angular_index'
        post '/delete', to: 'stamps#delete'
      end
    end

    resources :categories do 
      collection do
        get '/angular_index', to: 'categories#angular_index'
        post '/delete', to: 'categories#delete'
      end
    end
  end

  scope :admin do
    resources :miscellaneous, :only => ['update', 'edit'] do
      post '/send_notifications_manual', to: 'miscellaneous#send_notifications_manual'
    end
  end

end

app/views/layouts/admin/_links_engines.html.haml
- Navbar.routes_admin.each do |key, link|
	%li{ class: "#{'active' if params[:controller].split("/").last.downcase == key}" }
		= link_to "/admin#{link}" do
			= raw t("engine.#{key}")

app/views/layouts/admin/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/admin/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
- if current_user
	%nav.navbar.navbar-default.navbar-fixed-top#admin-navbar.visible-xs
		.navbar-header
			- if current_user
				%button.navbar-toggle#button-navbar
					%span.sr-only Toggle navigation
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
			= link_to main_app.root_path do
				= image_tag "logo-blank.png", class: 'navbar-brand'
				= #image_tag "logo.png", class: 'navbar-brand visible-sm visible-xs'
		.collapse.navbar-collapse
			%ul.nav.navbar-nav.navbar-right.hidden-sm
				= render 'layouts/admin/navigation_links'

app/views/layouts/admin/_sidebar.html.haml
- if current_user
	.sidebar.affix 
		.perfil
			.name-avatar
				%p
					= current_user.name.split(" ").first
				.btn-group
					=link_to main_app.edit_user_path(current_user.id), class: 'btn btn-xs' do
						%i.fa.fa-edit
					= link_to main_app.destroy_user_session_path, :method=>'delete', class: 'btn btn-xs danger' do
						%i.fa.fa-power-off
		.title-sidebar
			NAVEGACIÓN
		%ul.nav.nav-sidebar.title-components
			= render "layouts/admin/sidebar_links"

app/views/layouts/admin/_sidebar_links.html.haml
%li{ class: "#{'active' if params[:controller] == 'admin'}" }
  = link_to main_app.admin_index_path do
    %i.fa.fa-desktop
    Dashboard
%li{ class: "#{'active' if params[:controller] == 'ods' or params[:controller] == 'attachments' or params[:controller] == 'validations'}" }
  = link_to main_app.ods_path do
    %i.fa.fa-truck
    Ordenes
- unless current_user.has_role? :diseñador
  %li{ class: "#{'active' if params[:controller] == 'reorders'}" }
    = link_to main_app.reorders_path do
      %i.fa.fa-file-text
      Cotizaciones
= render "layouts/admin/links_engines"
- if can? :index, User and current_user.has_role? :admin
  %li{ class: "#{'active' if params[:controller] == 'users'}" }
    = link_to main_app.users_path do
      %i.fa.fa-user
      =t t('user.model')
- if current_user.has_role? :admin
  %li{ class: "#{'active' if params[:controller] == 'stamps'}" }
    = link_to stamps_path do
      %i.fa.fa-hdd-o
      Sellos
  %li{ class: "#{'active' if params[:controller] == 'categories'}" }
    = link_to categories_path do
      %i.fa.fa-tags
      Categorías
  %li{ class: "#{'active' if params[:controller] == 'miscellaneous'}" }
    = link_to edit_miscellaneou_path(1) do
      %i.fa.fa-cog
      Configuración

%li.visible-xs
  = link_to main_app.root_path do
    = "<i class='fa fa-reply'></i> #{t("navbar-admin.website")}".html_safe

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'LithoXpress Online - Consulta de Ordenes'
    %link{:href => "http://fonts.googleapis.com/css?family=Titillium+Web:300", :rel => "stylesheet", :type => "text/css"}/
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'LithoXpress Online - Consulta de Ordenes'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
    = favicon_link_tag "favicon.ico"
  %body#admin{style:"font-family: 'Titillium Web', sans-serif;background: #f2f2f2;"}
    %header
      = render 'layouts/admin/navigation'
    %main{:role => "main"}
      .row.fluid
        = render 'layouts/admin/sidebar'
        - if params[:controller] == 'devise/sessions' or  params[:controller] == 'devise/passwords'#vista para login
          .col-lg-12.margin-login
            - flash.each do |name, msg|
              - if msg.is_a?(String)
                %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", style: "margin-bottom:10px;"}
                  %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                  = content_tag :div, msg, :id => "flash_#{name}"
            = yield
        - if params[:controller] == 'users' and params[:action] == 'sign_up' #vista para login
          .col-lg-12
            = yield
        - if current_user #vista para current_user
          .main
            .title-admin
              .row
                .col-lg-12.col-md-12.col-sm-12.name-title
                  = raw t("controllers.#{params[:controller].split("/").last.downcase}")
                  = " - "+t("admin.actions.#{params[:action].downcase}") unless params[:controller] == 'admin'

            = yield

    - if not current_user
      %footer{style:"padding-bottom:20px;margin-top:10%;"}
        %div
          %center
            Todos los derechos reservados 
            %span
              %i.fa.fa-copyright
            Litoxpress 2015 | Desarrollado por 
            = image_tag "slicegroup.png", width: "50px", style: "display:inline; margin-left: 1px;"

      
    