config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :validations, :only => ['new', 'update', 'edit']
  post 'validations/:id' => 'validations#create', :as => 'create_validation'
  get 'catalog/stamps/:id' => 'visitors#catalog', :as => 'catalog'
  get 'catalog/modal/:stamp_id' => 'visitors#modal', :as => 'catalog_modal'
  get '/orders/update_terms' => 'orders#update_terms'
  post '/orders/create' => 'orders#create'
  post '/create' => 'orders#create'

  resources :attachments, :only => ['create', 'update', 'edit', 'destroy']

  root to: 'admin#index'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
  			get '/angular_index', to: 'users#angular_index'
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end

  scope :users do
    post '/registration', to: 'users#register', as: "register_user"
    get '/sign_up', to: 'users#sign_up', as: "sign_up_user"
  end

  resources :ods do
    collection do
      get '/angular_index', to: 'ods#angular_index'
      get ':id/clone', to: 'ods#clone', as: 'clone'
    end
  end

  resources :reorders, only: [:update, :edit, :destroy, :index, :show] do 
    collection do
      get '/angular_index', to: 'reorders#angular_index'
      post ':id/changed_status/:stat', to: 'reorders#changed_status', as: 'changed_status'
      post '/delete', to: 'reorders#delete'
    end
  end

  resources :orders, only: [:new, :create]

  scope :admin do
    resources :stamps do
      collection do
        get '/angular_index', to: 'stamps#angular_index'
        post '/delete', to: 'stamps#delete'
      end
    end

    resources :categories do 
      collection do
        get '/angular_index', to: 'categories#angular_index'
        post '/delete', to: 'categories#delete'
      end
    end
  end

  scope :admin do
    resources :miscellaneous, :only => ['update', 'edit'] do
      post '/send_notifications_manual', to: 'miscellaneous#send_notifications_manual'
    end
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :ods
  mount_uploader :image, ImageUploader

  validates_presence_of :image
  validate :picture_size_validation, :if => "image?"

  def picture_size_validation
   	errors[:image] << "Imagén no puede pesar más de 1 MB" if self.image.size > 1.megabytes
	end

	def name
    self.image.file.original_filename.split(".").first.gsub("_", " ")
  end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout 'admin/application'

  respond_to :html

  def index
    @attachments = Attachment.all
    respond_with(@attachments)
  end

  def show
    respond_with(@attachment)
  end

  def new
    @attachment = Attachment.new
    respond_with(@attachment)
  end

  def edit
  end

  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.save
    respond_with(@attachment)
  end

  def update
    @attachment.update(attachment_params)
    NotificationMailer.upload_design(Ods.find(@attachment.ods_id)).deliver #send email
    redirect_to edit_od_path(attachment_params[:ods_id])
  end

  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to edit_od_path(@attachment.ods_id), notice: t("notification.delete") }
    end
  end

  private
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    def attachment_params
      params.require(:attachment).permit(:ods_id, :image, :choose_model, :description)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.haml
%div{ style: "padding:30px; padding-bottom:0px;"}
	.panel.panel-default
		.panel-heading
			Sustituir boceto
		= simple_form_for(@attachment) do |f|
			.panel-body
				.field
					= f.input :ods_id, as: :hidden
					= image_tag @attachment.image, class: "thumbnail"
					%br
					= f.input :image, label: false
					%br
					%label Descripción
					= f.input :description, label: false, input_html: { class: "form-control" }
			.panel-footer
				= link_to "Volver", od_path(@attachment.ods_id), class: "btn btn-default"
				= f.submit "Actualizar", class: "pull-right btn btn-warning"
				.clearfix
		

:javascript
	$(":file").filestyle({buttonBefore: true});

app/views/attachments/edit.html.haml
= render 'form'

app/views/attachments/index.html.haml
%h1 Listing attachments

%table
  %tr
    %th Ods
    %th Image
    %th
    %th
    %th

  - @attachments.each do |attachment|
    %tr
      %td= attachment.ods_id
      %td= attachment.image
      %td= link_to 'Show', attachment
      %td= link_to 'Edit', edit_attachment_path(attachment)
      %td= link_to 'Destroy', attachment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Attachment', new_attachment_path

app/views/attachments/new.html.haml
%h1 New attachment

= render 'form'

= link_to 'Back', attachments_path

app/views/attachments/show.html.haml
%p#notice= notice

%p
  %b Ods:
  = @attachment.ods_id
%p
  %b Image:
  = @attachment.image

= link_to 'Edit', edit_attachment_path(@attachment)
\|
= link_to 'Back', attachments_path