config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :validations, :only => ['new', 'update', 'edit']
  post 'validations/:id' => 'validations#create', :as => 'create_validation'
  get 'catalog/stamps/:id' => 'visitors#catalog', :as => 'catalog'
  get 'catalog/modal/:stamp_id' => 'visitors#modal', :as => 'catalog_modal'
  get '/orders/update_terms' => 'orders#update_terms'
  post '/orders/create' => 'orders#create'
  post '/create' => 'orders#create'

  resources :attachments, :only => ['create', 'update', 'edit', 'destroy']

  root to: 'admin#index'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
  			get '/angular_index', to: 'users#angular_index'
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end

  scope :users do
    post '/registration', to: 'users#register', as: "register_user"
    get '/sign_up', to: 'users#sign_up', as: "sign_up_user"
  end

  resources :ods do
    collection do
      get '/angular_index', to: 'ods#angular_index'
      get ':id/clone', to: 'ods#clone', as: 'clone'
    end
  end

  resources :reorders, only: [:update, :edit, :destroy, :index, :show] do 
    collection do
      get '/angular_index', to: 'reorders#angular_index'
      post ':id/changed_status/:stat', to: 'reorders#changed_status', as: 'changed_status'
      post '/delete', to: 'reorders#delete'
    end
  end

  resources :orders, only: [:new, :create]

  scope :admin do
    resources :stamps do
      collection do
        get '/angular_index', to: 'stamps#angular_index'
        post '/delete', to: 'stamps#delete'
      end
    end

    resources :categories do 
      collection do
        get '/angular_index', to: 'categories#angular_index'
        post '/delete', to: 'categories#delete'
      end
    end
  end

  scope :admin do
    resources :miscellaneous, :only => ['update', 'edit'] do
      post '/send_notifications_manual', to: 'miscellaneous#send_notifications_manual'
    end
  end

end

app/models/miscellaneou.rb
class Miscellaneou < ActiveRecord::Base
	validates_presence_of :email_design, :email_ventas, :email_support, :phone_support, :iva, :notification_time

	def notification_hours
		if self.notification_time.blank?
			"18".to_i
		else
			self.notification_time.split(":").first.to_i
		end
	end

	def notification_minutes
		if self.notification_time.blank?
			"30".to_i
		else
			self.notification_time.split(":").second.to_i
		end
	end
end

app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController
  before_action :set_miscellaneou, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource

  respond_to :html

  def index
    @miscellaneous = Miscellaneou.all
    respond_with(@miscellaneous)
  end

  def show
    respond_with(@miscellaneou)
  end

  def new
    @miscellaneou = Miscellaneou.new
    respond_with(@miscellaneou)
  end

  def edit
  end

  def create
    @miscellaneou = Miscellaneou.new(miscellaneou_params)
    @miscellaneou.save
    respond_with(@miscellaneou)
    reset_sidekiq
  end

  def update
    @miscellaneou.update(miscellaneou_params)
    if @miscellaneou.errors.blank?
      reset_sidekiq
      return redirect_to edit_miscellaneou_path(params[:id]),  flash: { notice: "Guardado con exito." }
    else
      respond_with(@miscellaneou)
    end
  end

  def destroy
    @miscellaneou.destroy
    respond_with(@miscellaneou)
  end

  def send_notifications_manual
    User.create_new_user_if_he_have_a_order(params[:date])
    User.send_notification_if_client_have_a_new_order(params[:date])
    redirect_to edit_miscellaneou_path(params[:miscellaneou_id]),  flash: { notice: "Correos enviados con exito." }
  end

  private
    def set_miscellaneou
      @miscellaneou = Miscellaneou.find(params[:id])
    end

    def miscellaneou_params
      params.require(:miscellaneou).permit(:email_design, :email_ventas, :iva, :email_support, :phone_support, :notification_time)
    end

    def reset_sidekiq
      system("bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -e production")
    end
end

app/helpers/miscellaneous_helper.rb
module MiscellaneousHelper
end

app/views/miscellaneous/_form.html.haml
= content_for(:title, "Admin - Configuración")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", style: 'margin-top:-20px; margin-bottom:10px;'}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
= simple_form_for(@miscellaneou) do |f|
	.panel.panel-default
		.panel-heading
			%i.fa.fa-th-list
			Datos de configuración
		.panel-body
			.form-inputs
				= f.input :email_design, label: false, input_html: { class: "form-control", placeholder: 'Email para administración de diseños' }
				%br
				= f.input :email_ventas, label: false, input_html: { class: "form-control", placeholder: 'Email para administración de ventas' }
				%br
				= f.input :email_support, label: false, input_html: { class: "form-control", placeholder: 'Email para soporte' }
				%br
				= f.input :phone_support, label: false, input_html: { class: "form-control", placeholder: 'Teléfono para soporte' }
				%br/
				= f.input :iva, label: false, input_html: { class: "form-control", placeholder: 'IVA' }
				%br/
				= f.input :notification_time, label: false, input_html: { class: "form-control", placeholder: 'Tiempo para enviar las notificaciones (Formato 24hrs)' }
		.panel-footer
			= f.button :submit, "Guardar", class: 'btn btn-warning pull-right'
			.clearfix

= simple_form_for("", url: miscellaneou_send_notifications_manual_path(@miscellaneou)) do |f|
	.panel.panel-default
		.panel-heading
			%i.fa.fa-th-list
			Envio de correos manual
		.panel-body
			.form-inputs
				= f.input :date, label: false, input_html: { class: "form-control", placeholder: 'Enviar correos a las ods creadas en esta fecha (formato: 2016-04-21)' }


		.panel-footer
			= f.button :submit, "Enviar", id: "send-btn",class: 'btn btn-warning pull-right', "data-loading-text"=>"Enviando..."
			.clearfix

:javascript
	$('#send-btn').on('click', function () {
		var $btn = $(this).button('loading')
	})

app/views/miscellaneous/edit.html.haml
%div{ style: "padding:30px; padding-bottom:0px;"}
	= render 'form'

app/views/miscellaneous/index.html.haml
%h1 Listing miscellaneous

%table
  %tr
    %th Email design
    %th Email ventas
    %th
    %th
    %th

  - @miscellaneous.each do |miscellaneou|
    %tr
      %td= miscellaneou.email_design
      %td= miscellaneou.email_ventas
      %td= link_to 'Show', miscellaneou
      %td= link_to 'Edit', edit_miscellaneou_path(miscellaneou)
      %td= link_to 'Destroy', miscellaneou, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Miscellaneou', new_miscellaneou_path

app/views/miscellaneous/new.html.haml
%h1 New miscellaneou

= render 'form'

= link_to 'Back', miscellaneous_path

app/views/miscellaneous/show.html.haml
%p#notice= notice

%p
  %b Email design:
  = @miscellaneou.email_design
%p
  %b Email ventas:
  = @miscellaneou.email_ventas

= link_to 'Edit', edit_miscellaneou_path(@miscellaneou)
\|
= link_to 'Back', miscellaneous_path