config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :validations, :only => ['new', 'update', 'edit']
  post 'validations/:id' => 'validations#create', :as => 'create_validation'
  get 'catalog/stamps/:id' => 'visitors#catalog', :as => 'catalog'
  get 'catalog/modal/:stamp_id' => 'visitors#modal', :as => 'catalog_modal'
  get '/orders/update_terms' => 'orders#update_terms'
  post '/orders/create' => 'orders#create'
  post '/create' => 'orders#create'

  resources :attachments, :only => ['create', 'update', 'edit', 'destroy']

  root to: 'admin#index'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
  			get '/angular_index', to: 'users#angular_index'
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end

  scope :users do
    post '/registration', to: 'users#register', as: "register_user"
    get '/sign_up', to: 'users#sign_up', as: "sign_up_user"
  end

  resources :ods do
    collection do
      get '/angular_index', to: 'ods#angular_index'
      get ':id/clone', to: 'ods#clone', as: 'clone'
    end
  end

  resources :reorders, only: [:update, :edit, :destroy, :index, :show] do 
    collection do
      get '/angular_index', to: 'reorders#angular_index'
      post ':id/changed_status/:stat', to: 'reorders#changed_status', as: 'changed_status'
      post '/delete', to: 'reorders#delete'
    end
  end

  resources :orders, only: [:new, :create]

  scope :admin do
    resources :stamps do
      collection do
        get '/angular_index', to: 'stamps#angular_index'
        post '/delete', to: 'stamps#delete'
      end
    end

    resources :categories do 
      collection do
        get '/angular_index', to: 'categories#angular_index'
        post '/delete', to: 'categories#delete'
      end
    end
  end

  scope :admin do
    resources :miscellaneous, :only => ['update', 'edit'] do
      post '/send_notifications_manual', to: 'miscellaneous#send_notifications_manual'
    end
  end

end

app/models/reorder.rb
class Reorder < ActiveRecord::Base
	belongs_to :user
	belongs_to :ods

	validates_presence_of :cantidad, :price, :emision_date
	validates_numericality_of :price, greater_than_or_equal_to: 0
	validates_numericality_of :emision_date, greater_than_or_equal_to: 0

	def self.por_aprobar
		Reorder.where(["status = ?", "Por aprobar"]).count
	end

	def as_json(options={})
		{
			id: self.id,
			client_name: Cliempre.find_by_codigo(Ods.find(self.ods_id).Cliente).nombre,
			ods_id: self.ods_id,
			ods: self.ods,
			status: self.status,
			cantidad: self.cantidad,
			price: self.price,
			user: self.user.as_json,
			description: self.description.as_json,
			created_at: self.created_at,
			updated_at: self.updated_at
		}
	end
end

app/controllers/reorders_controller.rb
class ReordersController < ApplicationController
  before_action :set_reorder, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout 'admin/application'
  
  respond_to :html

  def index
    authorize_design(current_user)
    if current_user.has_role? :cliente
      @reorders = Reorder.where(user_id: current_user.id).order('id DESC')
    elsif current_user.has_role? :admin or current_user.has_role? :ventas
      @reorders = Reorder.all.reverse
    end
  end

  def angular_index
    authorize_design(current_user)
    if current_user.has_role? :cliente
      @reorders = Reorder.where(user_id: current_user.id).order('id DESC')
    elsif current_user.has_role? :admin or current_user.has_role? :ventas
      @reorders = Reorder.all.reverse
    end
    respond_to do |format|
      format.html
      format.json { render :json => @reorders  }
    end
  end

  def show
    @order = Ods.find(@reorder.ods_id)
    total = @reorder.price*@reorder.cantidad
    iva = Miscellaneou.first.iva/100
    @total_amount = total+(total*iva)
    respond_with(@reorder)
  end

  def new
    @reorder = Reorder.new
    respond_with(@reorder)
  end

  def edit
    authorize_user current_user
    validate_aprobation @reorder
  end

  def create
    @reorder = Reorder.new(reorder_params)
    @reorder.save
    respond_with(@reorder)
  end

  def update
    authorize_user current_user
    validate_aprobation @reorder
    @reorder.update(reorder_params)
    respond_with(@reorder)
  end

  def changed_status
    reorder = Reorder.find(params[:id])
    authorize_changed_status(current_user)
    
    
    if params[:stat] == '1' and reorder.status == "Por cotizar" and reorder.price > 0 and reorder.emision_date > 0
      reorder.update_attribute(:status, "Cotizada")
      NotificationMailer.status_reorder(reorder).deliver #send email
      redirect_to reorder_path(reorder.id), notice: "Cotización aprobada"
    elsif params[:stat] == '1' or reorder.price == 0 or reorder.emision_date == 0
      if reorder.price == 0
        return redirect_to reorder_path(reorder.id), flash: { danger: "La cotización debe tener un precio para poder ser cotizada." }
      elsif reorder.emision_date == 0
        return redirect_to reorder_path(reorder.id), flash: { danger: "La cotización debe tener los días de emision para poder ser cotizada" }
      end
    end

    if params[:stat] == '0' and reorder.status != "Por cotizar"
       authorize_undo_status(current_user)
       reorder.update_attribute(:status, "Por cotizar")
       redirect_to reorder_path(reorder.id), notice: "La cotización ha cambiado al estatus 'Por cotizar'"
    elsif params[:stat] == '2' and reorder.status == "Por cotizar"
        reorder.update_attribute(:status, "No cotizada")
        NotificationMailer.status_reorder(reorder).deliver #send email
        redirect_to reorder_path(reorder.id), notice: "Cotización desaprobada"
    elsif params[:stat] == '2' and reorder.status == "Cotizada"
        redirect_to reorder_path(reorder.id), flash: { danger: "Esta cotización ya ha sido aprobada, no se puede desaprobar." }
    end 
    
  end

  def destroy
    authorize_user current_user
    @reorder.destroy
    respond_with(@reorder)
  end

  def delete
    authorize_user current_user
    Reorder.destroy( redefine_destroy params[:ids].split(",") )
    respond_to do |format|
      format.html { render nothing: true }
    end
  end

  private
    def redefine_destroy(params)
      params.sort.each do |id|
        params.delete id unless Order.exists? id
      end
    end

    def set_reorder
      @reorder = Reorder.find(params[:id])
    end

    def reorder_params
      params.require(:reorder).permit(:cantidad, :stat, :price, :emision_date, :description)
    end

    #validations
    def authorize_design(user)
      if user.has_role? :diseñador
        raise CanCan::AccessDenied.new("No estas autorizado para gestionar el módulo de ordenes.", :show, Reorder)
      end
    end

    def authorize_user(user)
      unless !user.has_role? :diseñador
        raise CanCan::AccessDenied.new("Solo los clientes tienen acceso a este procedimiento.", :show, Reorder)
      end
    end

    def authorize_changed_status(user)
      unless user.has_role? :ventas or user.has_role? :admin
        raise CanCan::AccessDenied.new("No tiene acceso a este procedimiento.", :edit, Reorder)
      end
    end

    def authorize_undo_status(user)
      if !user.has_role? :admin
        raise CanCan::AccessDenied.new("Solo los administradores pueden deshacer los estatus.", :new, Order)
      end
    end

    def validate_aprobation(reorder)
      if reorder.status == "Cotizada"
        raise CanCan::AccessDenied.new("La orden ya ha sido cotizada, no puede editarla.", :new, Order)
      end
    end
end

app/helpers/reorders_helper.rb
module ReordersHelper
end

app/views/reorders/_form.html.haml
= simple_form_for(@reorder) do |f|
	.panel.panel-default
		.panel-heading
			%i.fa.fa-th-list
			- if action_name.eql?("edit")
				= "(#{@reorder.ods.OdsId}) #{@reorder.ods.Descripcion}"
			- else
				Datos de solicitud
		.panel-body
			.form-inputs
				%br
				%label Cantidad
				= f.input :cantidad, label: false, input_html: { class: "form-control", placeholder: 'Cantidad', step:'1', min:'1'}
				- if current_user.has_role? :ventas or current_user.has_role? :admin
					%br
					%label Precio
					= f.input :price, label: false, input_html: { class: "form-control", placeholder: 'Precio unitario', step:'1', min:'1'}
					%br
					%label Introduzca días de validez
					= f.input :emision_date, label: false, input_html: { class: "form-control", placeholder: 'Días de emisión', step:'1', min:'1'}
					%br
					%label Observacion
					= f.input :description, label: false, input_html: { class: "form-control", placeholder: 'Observacion'}
		.panel-footer
			= f.button :submit, "Guardar", class: "btn btn-warning pull-right"
			.clearfix

app/views/reorders/edit.html.haml
= content_for(:title, "Admin - Orden | Editar")
%div{ style: "padding:30px; padding-bottom:0px;"}
	= render 'form'

app/views/reorders/index.html.haml
= content_for(:title, "Admin - Cotizaciones")

%div{'ng-controller'=>'indexReorderCtrl',  'ng-init'=>'init()', style:"padding:30px;padding-bottom:0px;"}
	.angular
		.form-inline
			.form-group
				.input-group
					.input-group-addon
						%i.fa.fa-search
					%input#input-search{"ng-model" => "buscar.$", :placeholder => "Filtrar búsqueda", :type => "text"} 
		.alert{class: 'alert-{{statusAlert}}', 'ng-show'=>"alert==true"} 
			%strong Admin:    
			{{msnAlert}}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
		= render 'layouts/admin/messages'

		%br/
		.panel.panel-default
			.panel-heading
				- if current_user.has_role? :cliente
					%a.btn.btn-default{"ng-show" => "reorders.data.length", "ng-click" => "allSelected(reorders)", :title => t("admin.buttons.select_all") }
						%i.fa.fa-check-square-o
					%button#btn-delete.btn.btn-default{class: "btn-{{btnDelete}}", "ng-click" => "destroy()", :title => t("admin.buttons.trash") }
						%i.fa.fa-trash-o
				%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000"}
					Página {{page}}
				%button.btn.btn-default.pull-right{"ng-click" => "nextList();"}
					%i.fa.fa-arrow-right
				%button.btn.btn-default.pull-right{"ng-click" => "lastList();"}
					%i.fa.fa-arrow-left
				.clearfix
			.panel-body
				%table{style: "width:100%"}
					%tbody
						- if @reorders.count != 0
							%th{ "ng-show" => "reorders.data" }
							%th{ "ng-show" => "reorders.data" }
								%center
								Código de orden
							%th{ "ng-show" => "reorders.data" }
								%center
									Cliente
							%th{ "ng-show" => "reorders.data" }
								%center
									Descripción
							%th{ "ng-show" => "reorders.data" }
								%center
									Estatus de la cotización
							%th{ "ng-show" => "reorders.data" }
						%tr{ class: "select-{{reorder.checked}}", "ng-click" => "show(reorder.id)", :id => "row-{{reorder.id}}", "ng-repeat" => "reorder in reorders.data | filter:buscar | interval:interval_a:interval_b "}
							%td.messages{width: "1px;"}
								%input.check{:id => "check-{{reorder.id}}", "ng-click" => "selected(reorder.id); $event.stopPorpagation();", :type => "checkbox", "ng-model" => "reorder.checked"}
							%td.messages {{reorder.ods_id}}
							%td.messages {{reorder.client_name}}
							%td.messages {{ reorder.ods.descripcion }}
							%td.messages.hidden-xs
								.label.label-info{ "ng-if"=>"reorder.status == 'Por cotizar'", style: "font-size: 14px;"} {{ reorder.status }}
								.label.label-success{ "ng-if"=>"reorder.status == 'Cotizada'", style: "font-size: 14px;"} {{ reorder.status }}
								.label.label-danger{ "ng-if"=>"reorder.status == 'No cotizada'", style: "font-size: 14px;"} {{ reorder.status }}
							%td.messages
								= link_to "/reorders/{{reorder.id}}", title: t('admin.actions.show') do
									%i.fa.fa-exclamation-circle
								- if !current_user.has_role? :diseñador
									= link_to "/reorders/{{reorder.id}}/edit", title: t('admin.actions.edit'), "ng-if"=>"reorder.status != 'Cotizada'" do
										%i.fa.fa-edit
								- if current_user.has_role? :cliente
									= link_to "{{destroy_path(reorder.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estás seguro de querer eliminar esta cotización?' } do
										%i.fa.fa-trash-o
						%tr{"ng-show" => "!reorders.data.length"}
							%td{:style => "width:100%"}
								%center
									- if current_user.has_role? :cliente and current_user.reorders.count == 0
										No tienes cotizaciones
									- elsif current_user.has_role? :cliente and current_user.reorders.count != 0
										%i.fa.fa-spinner.fa-spin{ style: "font-size:30px; margin-bottom:10px;"}
										%br
										Espere unos segundos
									- elsif !current_user.has_role? :cliente and Reorder.count != 0
										%i.fa.fa-spinner.fa-spin{ style: "font-size:30px; margin-bottom:10px;"}
										%br
										Espere unos segundos
									- else
										No hay cotizaciones
							
			.panel-footer
				%center
					%strong {{ reorders.data.length }} 
					Cotizaciones

app/views/reorders/show.html.haml
= content_for(:title, "Admin - Reorden | #{@reorder.id}")
%div{ style: "padding:30px; padding-bottom:0px;"}
	- flash.each do |name, msg|
		- if msg.is_a?(String)
			%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", style: 'margin-top:-20px; margin-bottom:10px;'}
				%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
				= content_tag :div, msg, :id => "flash_#{name}"
	.panel.panel-default
		.panel-heading
			%i.fa.fa-exclamation-circle
			Datos de la cotización
		.panel-body
			%label Código de la orden a recotizar:
			= @reorder.ods_id
			%br
			%label Nombre del cliente:
			= User.find_by_cod(@order.Cliente).name
			%br/
			- unless current_user.has_role? :cliente
				%label Código del cliente:
				= @order.Cliente
				%br
			%label Fecha de la orden original:
			= @order.Fecha
			%br/
			%label Observación
			= @reorder.description
			%br/
			%label Descripción
			= @order.Descripcion
			%br/
			%label Para
			= @order.Para
			%br/
			%label Precio unitario:
			= @reorder.price == 0 ? "En espera de asignación de precio" : number_to_currency(@reorder.price, :precision => 2, format: "%n %u", unit: "Bs.")
			%br/
			%label Cantidad:
			=  number_with_precision(@reorder.cantidad, :precision => 0)
			%br/
			%label Total (incluye IVA):
			= @reorder.price*@reorder.cantidad == 0 ? "En espera de asignación de precio" : number_to_currency(@total_amount, :precision => 2, format: "%n %u", unit: "Bs.")
			%br/
			%label Fecha de cotización:
			= @reorder.created_at. strftime("%Y-%m-%d")
			%br
			- if @reorder.status == "Cotizada"
				%label Valida hasta:
				- date = @reorder.created_at+@reorder.emision_date.day 
				= date.strftime("%Y-%m-%d")
				- if current_user.has_role? :cliente
					.well{style:'margin-top:10px; margin-bottom:0px;'}
						%center
							%strong Nota: 
							Debe dirigirse a nuestra oficina para ordenar su trabajo.

			- elsif @reorder.status == "No cotizada"
				%label Estado:
				.label.label-danger{ style: "font-size: 14px;"}= @reorder.status
			- else
				%label Estado:
				.label.label-info{ style: "font-size: 14px;"}= @reorder.status

		.panel-footer
			- if !current_user.has_role? :diseñador
				= link_to 'Editar', edit_reorder_path(@reorder), class: 'btn btn-warning pull-right', style: "color: white; margin-left: 5px" if @reorder.status == "Por cotizar"

			- if current_user.has_role? :ventas or current_user.has_role? :admin and @reorder.status == "Por cotizar"
				= link_to 'No cotizar', changed_status_reorders_path(@reorder, 2), method: :post, :data => { :confirm => '¿Estas seguro de querer desaprobar?, luego no podrá deshacer este cambio.' }, class: 'btn btn-danger pull-right', style: "color: white;"
				= link_to 'Cotizar', changed_status_reorders_path(@reorder, 1), method: :post, :data => { :confirm => '¿Estas seguro de querer aprobar?, luego no podrá deshacer este cambio.' }, class: 'btn btn-success pull-right', style: "color: white; margin-right: 5px;"

			- if current_user.has_role? :admin and @reorder.status != "Por cotizar"
				= link_to 'Deshacer', changed_status_reorders_path(@reorder, 0), method: :post, :data => { :confirm => '¿Estas seguro de querer Deshacer?, esta acción cambiara el estado a "Por cotizar"' }, class: 'btn btn-warning pull-right', style: "color: white;"
			.clearfix